### ISSUE TITLE
Error when fitted = TRUE and log terms in formula

### ISSUE THREAD

**Issue by alexpghayes** [MarcoEnea/speedglm#1]
Same bug that I emailed you about, just documenting it here as well.

```r
speedglm::speedglm(hp ~ log(mpg), mtcars, fitted = TRUE)
#> Error in eval(predvars, data, env): object 'mpg' not found
```

Will try to get around to a PR at some point but no promises.

**Comment by MarcoEnea** [comment]
Bug fixed.

> speedglm(hp ~ log(mpg), mtcars, fitted = TRUE)
Generalized Linear Model of class 'speedglm':

Call:  speedglm(formula = hp ~ log(mpg), data = mtcars, fitted = TRUE) 

Coefficients:
(Intercept)     log(mpg)  
      684.3       -181.8
