### ISSUE TITLE
summary(model)$coefficients[['Pr(>|t|)']] should be numeric

### ISSUE THREAD

**Issue by vincentarelbundock** [MarcoEnea/speedglm#2]
At the moment, p values in the summary object are stored as a character vector:

``` r
library(speedglm)
library(broom)

x <- seq(1:100)
y <- 3.*x + rnorm(100)*3 + 5.
z <- sample(c('Young','Middle','Old'),100,replace=TRUE)
mod <- speedglm(y~x+z)
s <- summary(mod)
str(s$coefficients)
#> 'data.frame':    4 obs. of  4 variables:
#>  $ Estimate  : num  5.292 2.992 -0.164 -0.221
#>  $ Std. Error: num  0.8817 0.0116 0.844 0.9087
#>  $ t value   : num  6.003 258.434 -0.194 -0.243
#>  $ Pr(>|t|)  : chr  " 3.44e-08" "2.78e-138" " 8.46e-01" " 8.08e-01"
```

<sup>Created on 2020-07-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This poses problems for users or packages who want to extract p.values programmatically to, for instance, draw regression tables or coefficient plots. See here for the kinds of issues that arise:

https://github.com/tidymodels/broom/pull/881

Ideally, string formatting should be done in the `print.summary.speedglm` method, rather than in the `summary.speedglm` method:

https://github.com/MarcoEnea/speedglm/blob/master/R/summary.speedglm.r#L25

**Comment by MarcoEnea** [comment]
done

**Comment by vincentarelbundock** [comment]
thanks! much appreciated.
